### ISSUE TITLE
Barra lateral mobile continua ativa mesmo depois de fazer a transição para versão desktop

### ISSUE THREAD

**Issue by ammliee** [RickyHideki/hideki-portfolio#2]
### Passos para reproduzir:

- Vá para a versão mobile do site
- Abra o menu lateral
- Mude para a versão desktop
- Ta ai, o menu lateral continua aberto.

![image](https://user-images.githubusercontent.com/54507932/131931613-21b36d1d-7920-4dfe-95f9-0a52262df156.png)

**Comment by RickyHideki** [comment]
Problema corrigido! Eu tinha esquecido de colocar "display: none" no css da nav.
